apiVersion: v1
kind: ConfigMap
metadata:
  name: video-worker-config
data:
  AWS_REGION: "us-east-1"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/891377213431/video-upload-queue"
  S3_BUCKET_NAME: "hackathon-fiap-bucket"