apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processing-service
  labels:
    app: video-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-processing-service
  template:
    metadata:
      labels:
        app: video-processing-service
    spec:
      containers:
        - name: video-processing-service
          image: 891377213431.dkr.ecr.us-east-1.amazonaws.com/video-processing-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: video-processing-service-config
            - secretRef:
                name: video-processing-service-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"