apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - secret.yaml

images:
  - name: video-processing-service
    newName: 891377213431.dkr.ecr.us-east-1.amazonaws.com/video-processing-service
    newTag: latest

commonLabels:
  app: video-processing-service